# -*- coding: utf-8 -*-
"""7. 파이토치를 이용한 cnn 핵심모듈구현.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PmKOWam-m4rmSPEdGRmDcvHj7UQC3JB3

# 목표

- CNN에서 합성곱이 어떤식으로 처리되는지 이해
  - 데이터의 변화 확인(이미지)
- CNN에서 풀링이 어떤식으로 처리되는지 이해
  - 데이터의 변화 확인(이미지)
- 편향, 패딩은 고정하고 사용
- x, W, s, p 간의 공식 확인
- W를 직접 설계(수직, 수평, 빛의 방향 검토)
"""

import torch
torch.__version__

"""# 이미지 준비"""

import matplotlib.pyplot as plt
# Plilow
from PIL import Image

img = Image.open('/content/drive/MyDrive/ComputerProgramming/DeepLearning/2.딥러닝/dl/torch3.png')
img

import numpy as np

tmp = np.array( img )
tmp.shape, img.size
# (세로, 가로, 채널)

# 칼라이미지를 grayscale로 처리해서 1채널 이미지로 컨버팅
img = img.convert("L")
# L = R*(299/1000) + G*(나머지값/1000) + B*(114/1000)
img

# 1채널 이미지라서 채널값 자체가 사라졌다
tmp = np.array( img )
tmp.shape, img.size

img_Tensor = torch.Tensor(tmp)
img_Tensor.size()